spring:
  application:
    name: homework07

  datasource:
    url: jdbc:mysql://localhost:3306/homework07?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false
    username: homework07
    password: Kafuu7NoKawa1!
    driver-class-name: com.mysql.cj.jdbc.Driver

  thymeleaf:
    cache: false

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

server:
  port: 8080

app:
  jwt:
    secret: change_this_to_a_long_random_secret_key_please
    expiration-ms: 86400000
  captcha:
    session-key: CAPTCHA_CODE
